### ISSUE TITLE
methods

### ISSUE THREAD

**Issue by Keiserg** [blacknbunny/mcreator#3]
it's quite impressive i would like an explanation of the used techniques of possible

**Comment by blacknbunny** [comment]
strstr : http://blog.deepsec.net/?p=1613

toomuchmem : The  main  limit  with  AV  scanner  is  the  amount  of  time  they  can  spend  on  each  file.  During  a  regular system scan, AV will have to analyze thousands of files. It just cannot spend too much time or power on a peculiar one (it could also lead to a form of Denial Of Service attack on the AV). The simplest method to bypass AV just consists into buying enough time before the code is decrypted. A simple Sleepwon’t do the trick, AV emulator have  adapted to that. There are however plenty of methods to gaintime. This iscalled“Offer you have to refuse” because it imposes the AV to go through some code which consume too much resources thus we are sure the AV will abandon before the real code is started.

increments : An even easier method, which does not leave any systemtrace, consists into doing abasic operation for a sufficient number of time. In this case we use a forloop to increment one hundred millions of times a counter. This is enough to bypass AV, but it is nothing for a modern CPU. A  human being will not detect any difference when starting the code with or without this stub.

**Comment by blacknbunny** [comment]
Always.
